#### Fit Development GAMs ####
library(dplyr)
library(tidyverse)
library(cifti)
source("/cbica/projects/thalamocortical_development/code/thalamocortical_development/gam_functions/GAM_functions_thalamocortical.R")

############################################################################################################
#### Prepare Data ####

#Glasser regions with corresponding labels and tract names
glasser.regions <- read.csv("/cbica/projects/thalamocortical_development/Maps/parcellations/surface/glasser360_regionlist.csv") #parcel name, label name 
glasser.regions$tract <- paste0("thalamus_", glasser.regions$orig_parcelname) %>% gsub("_ROI", "_autotrack", .) %>% gsub("-", "_", .) #create tract variable with format thalamus_$hemi_$region_autotrack, no dashes -

#Dataset-specific tract lists for analysis
tractlist <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_tractlist_primary.csv") #generated by tract_measures/tractlists/thalamocortical_tractlists_HBN.R

#Dataset-specific tract diffusion measures
FA.glasser.hbn <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_FA_finalsample_primary.csv")
FA.glasser.hbn$sex <- as.factor(FA.glasser.hbn$sex)

############################################################################################################
#### Region-wise GAM Statistics and Derivative-based Temporal Developmental Properties ####

run_gam.fit.smooth <- function(dwi.measure, dwi.atlas, dwi.dataset, smooth.var, covs, k, fixed_edf){
  smooth.characteristics <- map_dfr(tractlist$tract, 
                                     function(x){as.data.frame(gam.fit.smooth(measure = dwi.measure, atlas = dwi.atlas, dataset = dwi.dataset, 
                                                                              region = as.character(x), smooth_var = smooth.var, covariates = covs, 
                                                                              knots = k, set_fx = fixed_edf))}) 
  write.csv(smooth.characteristics, sprintf("/cbica/projects/thalamocortical_development/thalamocortical_results/development_results/development_gameffects_%s_%s_%s.csv", dwi.measure, dwi.atlas, dwi.dataset), quote = F, row.names =F)
}

#HBN
run_gam.fit.smooth(dwi.measure = "FA", dwi.atlas = "glasser", dwi.dataset = "hbn", smooth.var = "age", covs = "sex + mean_fd", k = 3, fixed_edf = TRUE)

############################################################################################################
#### Region-wise GAM Fitted Value Predictions ####

run_gam.smooth.predict <- function(dwi.measure, dwi.atlas, dwi.dataset, smooth.var, covs, k, fixed_edf, num.pred){
  smooth.fittedvals <- map_dfr(tractlist$tract, 
                               function(x){as.data.frame(gam.smooth.predict(measure = dwi.measure, atlas = dwi.atlas, dataset = dwi.dataset, 
                                                                            region = as.character(x), smooth_var = smooth.var, covariates = covs, 
                                                                            knots = k, set_fx = fixed_edf, increments = num.pred)) %>% mutate(tract = x)})
  write.csv(smooth.fittedvals, sprintf("/cbica/projects/thalamocortical_development/thalamocortical_results/development_results/development_fittedvalues_%s_%s_%s.csv", dwi.measure, dwi.atlas, dwi.dataset), quote = F, row.names =F)
}

#HBN
run_gam.smooth.predict(dwi.measure = "FA", dwi.atlas = "glasser", dwi.dataset = "hbn", smooth.var = "age", covs = "sex + mean_fd", k = 3, fixed_edf = TRUE, num.pred = 200)

############################################################################################################
#### Region-wise GAM Smooth Estimates ####

run_gam.estimate.smooth <- function(dwi.measure, dwi.atlas, dwi.dataset, smooth.var, covs, k, fixed_edf, num.pred){
  smooth.centered <- map_dfr(tractlist$tract, 
                             function(x){as.data.frame(gam.estimate.smooth(measure = dwi.measure, atlas = dwi.atlas, dataset = dwi.dataset, 
                                                                           region = as.character(x), smooth_var = smooth.var, covariates = covs, 
                                                                           knots = k, set_fx = fixed_edf, increments = num.pred)) %>% mutate(tract = x)})
  write.csv(smooth.centered, sprintf("/cbica/projects/thalamocortical_development/thalamocortical_results/development_results/development_smoothcentered_%s_%s_%s.csv", dwi.measure, dwi.atlas, dwi.dataset), quote = F, row.names =F)
}

#HBN
run_gam.estimate.smooth(dwi.measure = "FA", dwi.atlas = "glasser", dwi.dataset = "hbn", smooth.var = "age", covs = "sex + mean_fd", k = 3, fixed_edf = TRUE, num.pred = 200)

############################################################################################################
#### Region-wise Developmental Derivatives ####

run_gam.derivatives <- function(dwi.measure, dwi.atlas, dwi.dataset, smooth.var, covs, k, fixed_edf, num.draws, num.pred, credible.interval){
  smooth.derivatives <- map_dfr(tractlist$tract, 
                             function(x){as.data.frame(gam.derivatives(measure = dwi.measure, atlas = dwi.atlas, dataset = dwi.dataset, 
                                                                       region = as.character(x), smooth_var = smooth.var, covariates = covs, 
                                                                       knots = k, set_fx = fixed_edf, draws = num.draws, 
                                                                       increments = num.pred, return_posterior_derivatives = credible.interval)) %>% mutate(tract = x)})
  write.csv(smooth.derivatives, sprintf("/cbica/projects/thalamocortical_development/thalamocortical_results/development_results/development_derivatives_%s_%s_%s.csv", dwi.measure, dwi.atlas, dwi.dataset), quote = F, row.names =F)
}

#HBN
run_gam.derivatives(dwi.measure = "FA", dwi.atlas = "glasser", dwi.dataset = "hbn", smooth.var = "age", covs = "sex + mean_fd", k = 3, fixed_edf = TRUE, num.draws = 1, num.pred = 200, credible.interval = FALSE)