#### Fit Environment GAMs ####
library(dplyr)
library(tidyverse)
library(cifti)
library(datawizard)
source("/cbica/projects/thalamocortical_development/code/thalamocortical_development/gam_functions/GAM_functions_thalamocortical.R")

############################################################################################################
#### Prepare Data ####

#### PNC 

# Sample-specific tract list
tractlist.pnc <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_tractlist_primary.csv") #generated by tract_measures/tractlists/thalamocortical_tractlists.R
tractlist.pnc <- tractlist.pnc %>% arrange(tract) #alphabetical order

# PNC diffusion measures
FA.glasser.pnc <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_FA_finalsample_primary.csv")
FA.glasser.pnc$sex <- as.factor(FA.glasser.pnc$sex)

# PNC environment measures
## neighborhood environment (envSES)
neighborhood.environment.pnc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/n1601_go1_environment_factor_scores_tymoore_20150909.csv")
id.key <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/bblid_scanid_reid.csv")
neighborhood.environment.pnc <- merge(id.key, neighborhood.environment.pnc, by = c("scanid", "bblid"), sort = F) %>%
                            select(rbcid, envSES) %>% mutate(rbcid = paste0("sub-", rbcid))
## household environment (mean parental education years)
household.environment.pnc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/n1601_demographics_go1_20161212.csv")
household.environment.pnc <- merge(id.key, household.environment.pnc, by = c("scanid"), sort = F) %>% 
                         select(rbcid, fedu1, medu1) %>% mutate(rbcid = paste0("sub-", rbcid)) 
household.environment.pnc$parental.education.years <- household.environment.pnc %>% select(fedu1, medu1) %>% rowMeans(na.rm = TRUE) #mean parental education measure

environment <- merge(neighborhood.environment.pnc, household.environment.pnc, by = "rbcid", sort = F)
FA.glasser.pnc <- merge(FA.glasser.pnc, environment, by = "rbcid", sort = F) 

#### HCPD 

# Sample-specific tract list
tractlist.hcpd <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_tractlist_primary.csv")
tractlist.hcpd <- tractlist.hcpd %>% arrange(tract) #alphabetical order

# HCPD diffusion measures
FA.glasser.hcpd <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_FA_finalsample_primary.csv")
FA.glasser.hcpd$sex <- as.factor(FA.glasser.hcpd$sex)

# HCPD environment measures
## household environment (categorical maternal education and mean parental education years)
household.environment.hcpd <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_demographics.tsv", sep = "\t") %>% select(participant_id, paternal_parent_education, maternal_parent_education)
names(household.environment.hcpd)[1] <- "rbcid"

household.environment.categorical <- household.environment.hcpd %>% select(rbcid, maternal_parent_education) %>%
  mutate_at(c("maternal_parent_education"), ~((recode_factor(.,"2nd Grade" = "No_HS_diploma", "2nd Grade;" = "No_HS_diploma", "4th Grade" = "No_HS_diploma", "6th Grade" = "No_HS_diploma", "7th Grade"= "No_HS_diploma", "8th Grade" = "No_HS_diploma", "8th Grade;" = "No_HS_diploma", "9th Grade"= "No_HS_diploma","9th Grade;"= "No_HS_diploma",
                                                             "10th Grade"= "No_HS_diploma", "10th Grade;" = "No_HS_diploma", "11th Grade"= "No_HS_diploma", "11th Grade;"= "No_HS_diploma",  "12th Grade"= "HS_diploma", "High School Diploma" = "HS_diploma", "Some College" = "Some_college", "Associate\'s Degree"= "Bachelor_degree", "Bachelor\'s Degree"= "Bachelor_degree",
                                                             "Doctoral Degree" = "Postgraduate_degree", "Master\'s Degree" = "Postgraduate_degree", "Professional Degree" = "Postgraduate_degree",
                                                             .ordered = TRUE)))) %>% rename(maternal_education_categorical = maternal_parent_education)


household.environment.years <- household.environment.hcpd %>% select(rbcid, maternal_parent_education, paternal_parent_education) %>%
  mutate_at(c("maternal_parent_education", "paternal_parent_education"), ~as.numeric((recode(.,"2nd Grade" = 2, "2nd Grade;" = 2, "4th Grade" = 4, "6th Grade" = 6, "7th Grade"= 7, "8th Grade" = 8, "8th Grade;" = 8, "9th Grade"= 9,"9th Grade;"= 9,
                                                             "10th Grade"= 10, "10th Grade;" = 10, "11th Grade"= 11, "11th Grade;"= 11,  "12th Grade"= 12, "High School Diploma" = 12, "Some College" = 14, "Associate\'s Degree"= 14, "Bachelor\'s Degree"= 16,
                                                             "Doctoral Degree" = 22, "Master\'s Degree" = 18, "Professional Degree" = 19, .default = NaN)))) %>% rename(maternal_education_years = maternal_parent_education) %>% rename(paternal_education_years = paternal_parent_education)
household.environment.years$parental.education.years <- household.environment.years %>% select(maternal_education_years, paternal_education_years) %>% rowMeans(na.rm = TRUE) #mean parental education measure

household.environment.hcpd <- merge(household.environment.categorical, household.environment.years, by = "rbcid", sort = F)
FA.glasser.hcpd <- merge(FA.glasser.hcpd, household.environment.hcpd, by = "rbcid", sort = F)

## household income-to-needs (national and state-adjusted)
household.INR.hcpd <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_INR.csv") %>% select(id, NEW_INCOME, INR_NATIONAL_PLINE, INR_STATE_RLINE)
names(household.INR.hcpd)[1] <- "rbcid"
household.INR.hcpd$rbcid <- gsub("HCD", "sub-", household.INR.hcpd$rbcid)
household.INR.hcpd <- household.INR.hcpd[household.INR.hcpd$rbcid %in% FA.glasser.hcpd$rbcid,]

household.INR.hcpd <- household.INR.hcpd %>% filter(NEW_INCOME != "999999" & NEW_INCOME != "9999999" & NEW_INCOME != "99999999" & NEW_INCOME != "9999999999" & !is.na(INR_NATIONAL_PLINE) & !is.na(INR_STATE_RLINE)) #exclude repeating-9 and NA entries, which indicate missing data (n = 23)
household.INR.hcpd <- household.INR.hcpd %>% filter(NEW_INCOME > 500 & NEW_INCOME != "1e+13") #exclude extreme (and likely erroneously reported) family income values (e.g., "80" for the year or ten trillion for the year) (n = 4)
household.INR.hcpd$INR_NATIONAL_PLINE <- winsorize(data = household.INR.hcpd$INR_NATIONAL_PLINE, threshold = 0.01, method = "percentile") #winzorize
household.INR.hcpd$INR_NATIONAL_PLINE <- log(household.INR.hcpd$INR_NATIONAL_PLINE) #take the natural log
household.INR.hcpd$INR_STATE_RLINE <- winsorize(data = household.INR.hcpd$INR_STATE_RLINE, threshold = 0.01, method = "percentile") #winzorize
household.INR.hcpd$INR_STATE_RLINE <- log(household.INR.hcpd$INR_STATE_RLINE) #take the natural log

FA.glasser.hcpd <- left_join(FA.glasser.hcpd, household.INR.hcpd, by = "rbcid")

############################################################################################################
####  PNC Analysis: Neighborhood (envSES) and Household (parental education years) Environment ####
############################################################################################################
#### Neighborhood Environment Effects: PNC

cor.test(FA.glasser.pnc$envSES, FA.glasser.pnc$mean_fd, method = c("spearman")) #rho = 0.03776212, p-value = 0.2017

### Main Effects (envSES, Linear Covariate)
neighborhoodenv.maineffects.pnc <- map_dfr(tractlist.pnc$tract, 
                                    function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                             region = as.character(x), smooth_var = "age", 
                                                                             covariate.interest = "envSES" , covariates.noninterest = "sex + mean_fd",
                                                                             knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(neighborhoodenv.maineffects.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/envSES_maineffects_FA_glasser_pnc.csv", quote = F, row.names =F)

### Developmental Trajectories (Fitted Values) by envSES Percentiles 
#predicted fitted values for 10th percentile neighborhood factor score
smooth.fittedvals.lowerpercentile <- map_dfr(tractlist.pnc$tract, 
                               function(x){as.data.frame(gam.smooth.predict.covariateinteraction(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                            region = as.character(x), smooth_var = "age", 
                                                                            int_var = "envSES", int_var.predict = quantile(FA.glasser.pnc$envSES, c(.1)),
                                                                            covariates = "sex + mean_fd", knots = 3, set_fx = TRUE, increments = 200)) %>% mutate(tract = x)})
smooth.fittedvals.lowerpercentile$envSES <- c("low")
#predicted fitted values for 90th percentile neighborhood factor score
smooth.fittedvals.upperpercentile <- map_dfr(tractlist.pnc$tract, 
                                             function(x){as.data.frame(gam.smooth.predict.covariateinteraction(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                                                               region = as.character(x), smooth_var = "age", 
                                                                                                               int_var = "envSES", int_var.predict = quantile(FA.glasser.pnc$envSES, c(.9)),
                                                                                                               covariates = "sex + mean_fd", knots = 3, set_fx = TRUE, increments = 200)) %>% mutate(tract = x)})
smooth.fittedvals.upperpercentile$envSES <- c("high")

smooth.fittedvals.byenvSES <- rbind(smooth.fittedvals.lowerpercentile, smooth.fittedvals.upperpercentile)
write.csv(smooth.fittedvals.byenvSES, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/devtrajectories_byenvSES_FA_glasser_pnc.csv", quote = F, row.names =F)

### Main Effects (envSES, Linear Covariate), controlling for Parental Education Years

FA.glasser.pnc <- FA.glasser.pnc %>% drop_na(parental.education.years) #remove 8 participants missing parental education data 

neighborhoodenv.maineffects.educontrol.pnc <- map_dfr(tractlist.pnc$tract, 
                                                      function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                                                  region = as.character(x), smooth_var = "age", 
                                                                                                  covariate.interest = "envSES" , covariates.noninterest = "sex + mean_fd + parental.education.years",
                                                                                                  knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(neighborhoodenv.maineffects.educontrol.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/envSES_maineffects_educontrolled_FA_glasser_pnc.csv", quote = F, row.names =F)

############################################################################################################
#### Household Environment Effects: PNC ####

### Main Effects (Parental Years of Education, Linear Covariate)
householdenv.maineffects.pnc <- map_dfr(tractlist.pnc$tract, 
                                           function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                                       region = as.character(x), smooth_var = "age", 
                                                                                       covariate.interest = "parental.education.years" , covariates.noninterest = "sex + mean_fd",
                                                                                       knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(householdenv.maineffects.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/householdSES_maineffects_FA_glasser_pnc.csv", quote = F, row.names =F)

### Main Effects (Parental Years of Education, Linear Covariate), controlling for envSES 
householdenv.maineffects.envSEScontrol.pnc <- map_dfr(tractlist.pnc$tract, 
                                        function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "pnc", 
                                                                                    region = as.character(x), smooth_var = "age", 
                                                                                    covariate.interest = "parental.education.years" , covariates.noninterest = "sex + mean_fd + envSES",
                                                                                    knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(householdenv.maineffects.envSEScontrol.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/householdSES_maineffects_envSEScontrolled_FA_glasser_pnc.csv", quote = F, row.names =F)


############################################################################################################
      #HCPD Analysis: Household (parental education and INR) Environment
############################################################################################################
#### Household Environment Effects: HCPD ####

### Main Effects (Parental Years of Education, Linear Covariate)
householdenv.maineffects.linear.hcpd <- map_dfr(tractlist.hcpd$tract, 
                                        function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "hcpd", 
                                                                                    region = as.character(x), smooth_var = "age", 
                                                                                    covariate.interest = "parental.education.years" , covariates.noninterest = "sex + mean_fd",
                                                                                    knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(householdenv.maineffects.linear.hcpd, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/householdSES_maineffects_linear_FA_glasser_hcpd.csv", quote = F, row.names =F)

### Main Effects (State-Adjusted Income to Needs Ratio)
FA.glasser.hcpd <- FA.glasser.hcpd %>% drop_na(INR_STATE_RLINE)

INRstate.maineffects.linear.hcpd <- map_dfr(tractlist.hcpd$tract, 
                                                function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "hcpd", 
                                                                                            region = as.character(x), smooth_var = "age", 
                                                                                            covariate.interest = "INR_STATE_RLINE" , covariates.noninterest = "sex + mean_fd",
                                                                                            knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(INRstate.maineffects.linear.hcpd, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/INRstate_maineffects_FA_glasser_hcpd.csv", quote = F, row.names =F)

INRnat.maineffects.linear.hcpd <- map_dfr(tractlist.hcpd$tract, 
                                            function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "hcpd", 
                                                                                        region = as.character(x), smooth_var = "age", 
                                                                                        covariate.interest = "INR_NATIONAL_PLINE" , covariates.noninterest = "sex + mean_fd",
                                                                                        knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(INRnat.maineffects.linear.hcpd, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/INRnat_maineffects_FA_glasser_hcpd.csv", quote = F, row.names =F)
