#### Fit Environment GAMs ####
library(dplyr)
library(tidyverse)
library(cifti)
source("/cbica/projects/thalamocortical_development/code/thalamocortical_development/gam_functions/GAM_functions_thalamocortical.R")

############################################################################################################
#### Prepare Data ####

#### HBN 

# Sample-specific tract list
tractlist <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_tractlist_primary.csv") #generated by tract_measures/tractlists/thalamocortical_tractlists_HBN.R
tractlist <- tractlist %>% arrange(tract) #alphabetical order

# HBN diffusion measures
FA.glasser.hbn <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_FA_finalsample_primary.csv")
FA.glasser.hbn$sex <- as.factor(FA.glasser.hbn$sex)

# HBN environment measures
## neighborhood environment (general SES)
neighborhood.environment.hbn <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HBN/HBN_General_SES.csv")
neighborhood.environment.hbn <- neighborhood.environment.hbn %>% mutate(rbcid = paste0("sub-", neighborhood.environment.hbn$GUID))

FA.glasser.hbn <- merge(FA.glasser.hbn, neighborhood.environment.hbn, by = "rbcid", sort = F) #13 individuals missing General_SES score, N = 946

############################################################################################################
####  HBN Analysis: Neighborhood Environment ####

#### Neighborhood Environment Effects: HBN

### Main Effects (envSES, Linear Covariate)
neighborhoodenv.maineffects.hbn <- map_dfr(tractlist$tract, 
                                    function(x){as.data.frame(gam.fit.covariate(measure = "FA", atlas = "glasser", dataset = "hbn", 
                                                                             region = as.character(x), smooth_var = "age", 
                                                                             covariate.interest = "General_SES" , covariates.noninterest = "sex + mean_fd",
                                                                             knots = 3, set_fx = TRUE))}) %>% select(tract, GAM.cov.tvalue, GAM.cov.pvalue) 
write.csv(neighborhoodenv.maineffects.hbn, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/generalSES_maineffects_FA_glasser_hbn.csv", quote = F, row.names =F)

### Developmental Trajectories (Fitted Values) by General_SES Percentiles 
#predicted fitted values for 10th percentile neighborhood factor score
smooth.fittedvals.lowerpercentile <- map_dfr(tractlist$tract, 
                               function(x){as.data.frame(gam.smooth.predict.covariateinteraction(measure = "FA", atlas = "glasser", dataset = "hbn", 
                                                                            region = as.character(x), smooth_var = "age", 
                                                                            int_var = "General_SES", int_var.predict = quantile(FA.glasser.hbn$General_SES, c(.1)),
                                                                            covariates = "sex + mean_fd", knots = 3, set_fx = TRUE, increments = 200)) %>% mutate(tract = x)})
smooth.fittedvals.lowerpercentile$envSES <- c("low")
#predicted fitted values for 90th percentile neighborhood factor score
smooth.fittedvals.upperpercentile <- map_dfr(tractlist$tract, 
                                             function(x){as.data.frame(gam.smooth.predict.covariateinteraction(measure = "FA", atlas = "glasser", dataset = "hbn", 
                                                                                                               region = as.character(x), smooth_var = "age", 
                                                                                                               int_var = "General_SES", int_var.predict = quantile(FA.glasser.hbn$General_SES, c(.9)),
                                                                                                               covariates = "sex + mean_fd", knots = 3, set_fx = TRUE, increments = 200)) %>% mutate(tract = x)})
smooth.fittedvals.upperpercentile$envSES <- c("high")

smooth.fittedvals.bygeneralSES <- rbind(smooth.fittedvals.lowerpercentile, smooth.fittedvals.upperpercentile)
write.csv(smooth.fittedvals.bygeneralSES, "/cbica/projects/thalamocortical_development/thalamocortical_results/environment_results/devtrajectories_bygeneralSES_FA_glasser_hbn.csv", quote = F, row.names =F)
