---
title: "HCPD Final Sample Selection: Thalamocortical Development"
author: "Valerie Jill Sydnor"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(purrr)
```

# Initial Participant List

```{r}
#list of RBC ids with processed, non-variant diffusion MRI data, N = 640
participants <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_NonVariantDWI_participantlist.txt", header=F) 
colnames(participants) <- c("rbcid") 
```

# Construct Final Sample

Health History Exclusion

```{r}
demographics <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_health_clinical.csv")
demographics$rbcid <- gsub("HCD", "sub-", demographics$src_subject_id) 
demographics <- demographics[demographics$rbcid %in% participants$rbcid,] #demographic, medical, and clinical information for just the N = 640 participants with diffusion MRI data
```

```{r}
# medhis_2e = cancer/leukemia
# medhis_2p = sickle cell anemia
# ms = multiple sclerosis
# ph_9 = has had a seizure
# cfmh_chd_seizure = has been to the doctor for epilepsy
# cfmh_chd_cerpalsy = has been to the doctor for cerebral palsy
# medhis_6j = has been knocked unconscious

healthexclude <- demographics %>% filter(medhis_2e == 1 | medhis_2p == 1 | ms == 1 | ph_9 == 1 | cfmh_chd_seizure == 1 | cfmh_chd_cerpalsy == 1 | medhis_6j == 1) %>% select(rbcid) #participants to exclude from the final study sample for medical or health history

participants.final <- participants[!participants$rbcid %in% healthexclude$rbcid,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 7 health exclude participants from the initial sample of 640 individuals with non-variant diffusion MRI data, remaining N = 633
```

Diffusion Acquisition Exclusion

```{r}
dwi.qc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by sample_construction/HCPD/diffusion_qcmetrics_HCPD.py
```

```{r}
acquisitionexclude <- dwi.qc %>% filter(raw_num_directions != 398) %>% select(subject_id) #participants to exclude from the final study sample for missing a diffusion MRI run, resulting in 298 or 299 diffusion directions instead of 398

participants.final <- participants.final[!participants.final$rbcid %in% acquisitionexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 8 participants from the sample of 633 health include individuals due to missing gradient directions, remaining N = 625
```

Diffusion Quality Exclusion

```{r}
qualityexclude <- dwi.qc %>% filter(t1_neighbor_corr < 0.6) %>% select(subject_id) #participants to exclude from the final study sample based on processed diffusion MRI T1 neighborhood correlation

participants.final <- participants.final[!participants.final$rbcid %in% qualityexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 15 participants from the sample of 625 due to diffusion data quality, remaining N = 610
```

Diffusion Scan Head Motion Exclusion

```{r}
motionexclude <- dwi.qc %>% filter(mean_fd > 1) %>% select(subject_id) #participants to exclude from the final study sample based on high in-scanner head motion during the diffusion runs

participants.final <- participants.final[!participants.final$rbcid %in% motionexclude$subject_id,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 24 participants from the sample of 610 due to in-scanner head motion, remaining N = 586
```

Age Range Exclusion 

```{r}
ageexclude <- demographics %>% filter(interview_age/12 < 8) %>% select(rbcid)

participants.final <- participants.final[!participants.final$rbcid %in% ageexclude$rbcid,] %>% as.data.frame() %>% setNames(c("rbcid")) #remove 14 participants (only 2.4% of the sample) from the sample of 586 due to young age, remaining N = 572
```

# Save Final Sample 

```{r}
write.csv(participants.final, "/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_thalamocortical_finalsample_N572.csv", quote = F, row.names = F)
```


