#### HCPD Diffusion Measure Harmonization and DF Creation ####
library(dplyr)
library(tidyr)
library(mgcv)
library(neuroCombat)

#### Prepare Demographics Data #### 
## Goal here is to get demographics data that will be used in model fitting for the final HCPD study sample

# HCPD final sample 
participants <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_thalamocortical_finalsample_N572.csv")

# Read in demographics, site information, and diffusion motion metrics
demographics <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_health_clinical.csv")
demographics$rbcid <- gsub("HCD", "sub-", demographics$src_subject_id) #format rbcid
demographics$age <- demographics$interview_age/12 #convert age from months to years
demographics <- demographics %>% select(rbcid, age, sex, site) #I'll have you, in the voice of Veruca Salt choosing a squirrel
demographics$sex <- as.factor(demographics$sex) #factor 
demographics$site <- as.factor(demographics$site) #factor 

dwi.qc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HCPD/HCPD_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by sample_construction/HCPD/diffusion_qcmetrics_HCPD.py
dwi.qc <- dwi.qc %>% select(subject_id, mean_fd) #I'll have you x2
colnames(dwi.qc) <- c("rbcid", "mean_fd")
demographics <- merge(demographics, dwi.qc, by = "rbcid")

demographics <- demographics[demographics$rbcid %in% participants$rbcid,] #covariates and site for final sample only

#### Prepare Diffusion Measure Spreadsheets ####

# Read in tract measures csv and create measure-specific spreadsheets
tractmeasures.glasser.hcpd <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_thalamocortical_measures.csv") #generated by tract_measures/diffusion_metrics/thalamocortical_dwimeasures.py

# Function to create measure-specific spreadsheets given long-formatted tract measure df and a dsi-studio measure of interest
extract_measure <- function(input.df, measure){ 
  measure.df <- get(input.df) %>% select(rbcid, tract, all_of(measure)) #extract measure of interest, long df
  measure.df <- measure.df %>% arrange(tract) #tracts in alphabetical order 
  measure.df <- measure.df %>% pivot_wider(names_from = "tract", values_from = all_of(measure)) #long to wide format, all participants and tracts
  measure.df <- measure.df %>% arrange(rbcid) #rbcids in numerical order
  measure.df <- left_join(demographics, measure.df, by = "rbcid") #final sample participants, all tracts + demographics
  colnames(measure.df) <- gsub("-", "_", colnames(measure.df))
  return(measure.df)
}

FA.glasser.hcpd <- extract_measure(input.df = "tractmeasures.glasser.hcpd", measure = "dti_fa")

MD.glasser.hcpd <- extract_measure(input.df = "tractmeasures.glasser.hcpd", measure = "md")

streamlinecount.glasser.hcpd <- extract_measure(input.df = "tractmeasures.glasser.hcpd", measure = "number_of_tracts")
write.csv(streamlinecount.glasser.hcpd, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_streamlinecount_finalsample.csv", quote = F, row.names = F)

#### Perform Combat Harmonization ####

#https://github.com/Jfortin1/neuroCombat_Rpackage/tree/2ccab2b42c59163717f012c70a54d20e8757b1c7 
#dat = pxn matrix of observations, p rows are features (here, tracts) and n columns are participants
#batch = a numeric or character vector of length n indicating batch (here, site)
#mod = model matrix of biological covariates, including the outcome of interest (here, age)
  # mod <- model.matrix(~ age + sex + mean_fd) 
  # mod contains intercept, age, mean_fd, sex #combat removes intercept from model matrix
  
# The harmonized matrix is stored in output$dat.combat

combat.input.fa <- t(FA.glasser.hcpd %>% select(contains("autotrack"))) #238 rows of tracts, 572 columns of participants
batch.input.fa <- FA.glasser.hcpd$site
mod.input.fa <- model.matrix(~ FA.glasser.hcpd$age + FA.glasser.hcpd$sex + FA.glasser.hcpd$mean_fd)
fa.harmonized.combat <- neuroCombat(dat = combat.input.fa, batch = batch.input.fa, mod = mod.input.fa)
FA.harmonized.hcpd <- fa.harmonized.combat$dat.combat %>% t() %>% data.frame() #572 rows of participants, 238 columns of tracts
FA.harmonized.hcpd <- cbind(FA.glasser.hcpd[,1:5], FA.harmonized.hcpd)

combat.input.md <- t(MD.glasser.hcpd %>% select(contains("autotrack"))) #238 rows of tracts, 572 columns of participants
batch.input.md <- MD.glasser.hcpd$site
mod.input.md <- model.matrix(~ MD.glasser.hcpd$age + MD.glasser.hcpd$sex + MD.glasser.hcpd$mean_fd)
md.harmonized.combat <- neuroCombat(dat = combat.input.md, batch = batch.input.md, mod = mod.input.md)
MD.harmonized.hcpd <- md.harmonized.combat$dat.combat %>% t() %>% data.frame()
MD.harmonized.hcpd <- cbind(MD.glasser.hcpd[,1:5], MD.harmonized.hcpd)

#### Create Final Diffusion Measure Spreadsheets Thresholded by Streamline Count ####
## Goal here is to NA out FA/MD information for connections with <5 streamlines (primary analysis) or <10 streamlines (sensitivity analysis), leaving dfs with only to-be-analyzed connections

# First, ensure that order of variables/tracts and rbcids is equivalent across dfs
identical(names(FA.glasser.hcpd), names(streamlinecount.glasser.hcpd))
identical(FA.glasser.hcpd$rbcid, streamlinecount.glasser.hcpd$rbcid)
identical(names(MD.glasser.hcpd),names(streamlinecount.glasser.hcpd))
identical(MD.glasser.hcpd$rbcid, streamlinecount.glasser.hcpd$rbcid)

# Next, threshold streamline count 
## primary threshold
streamlinecount.threshold5 <- ifelse(streamlinecount.glasser.hcpd[,6:243] >= 5, 1, NA) %>% data.frame() #set tracts with < 5 streamlines to NA, 6:243 cols are the tract cols

FA.glasser.hcpd.primary <- FA.glasser.hcpd[,6:243] * streamlinecount.threshold5 #don't analyze connections with < 5 streamlines. #rbcid order and tract order are identical between multiplied dfs
FA.glasser.hcpd.primary <- cbind(FA.glasser.hcpd[,1:5], FA.glasser.hcpd.primary)
write.csv(FA.glasser.hcpd.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_FA_finalsample_primary.csv", quote = F, row.names = F)

MD.glasser.hcpd.primary <- MD.glasser.hcpd[,6:243] * streamlinecount.threshold5 
MD.glasser.hcpd.primary <- cbind(MD.glasser.hcpd[,1:5], MD.glasser.hcpd.primary)
write.csv(MD.glasser.hcpd.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_MD_finalsample_primary.csv", quote = F, row.names = F)

## sensitivity threshold
streamlinecount.threshold10 <- ifelse(streamlinecount.glasser.hcpd[,6:243] >= 10, 1, NA) %>% data.frame() 

FA.glasser.hcpd.sensitivity <- FA.glasser.hcpd[,6:243] * streamlinecount.threshold10 
FA.glasser.hcpd.sensitivity <- cbind(FA.glasser.hcpd[,1:5], FA.glasser.hcpd.sensitivity)
write.csv(FA.glasser.hcpd.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_FA_finalsample_sensitivity.csv", quote = F, row.names = F)

MD.glasser.hcpd.sensitivity <- MD.glasser.hcpd[,6:243] * streamlinecount.threshold10 
MD.glasser.hcpd.sensitivity <- cbind(MD.glasser.hcpd[,1:5], MD.glasser.hcpd.sensitivity)
write.csv(MD.glasser.hcpd.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HCPD/HCPD_MD_finalsample_sensitivity.csv", quote = F, row.names = F)

