#### HBN Diffusion Measure Harmonization and DF Creation ####
library(dplyr)
library(tidyr)
library(mgcv)
library(neuroCombat)

#### Prepare Demographics Data #### 
## Goal here is to get demographics data that will be used in model fitting for the final HBN study sample

# HBN final sample 
participants <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HBN/HBN_thalamocortical_finalsample_N959.csv") #generated by finalsample_HBN.Rmd

# Read in demographics, site information, and diffusion motion metrics
demographics <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HBN/hbn_participants.tsv", sep = "\t")
colnames(demographics)[1] <- c("rbcid")
demographics <- demographics %>% filter(study_site != "HBNsiteSI") #remove this level from the factor (important for combat)
demographics <- demographics %>% select(rbcid, age, sex, study_site) 
demographics$sex <- as.factor(demographics$sex) #factor 
demographics$study_site <- as.factor(demographics$study_site) #factor 

dwi.qc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/HBN/HBN_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by sample_construction/HBN/diffusion_qcmetrics_HBN.py
dwi.qc <- dwi.qc %>% select(subject_id, mean_fd) #only need mean_fd for harmonization
colnames(dwi.qc) <- c("rbcid", "mean_fd")
demographics <- merge(demographics, dwi.qc, by = "rbcid") #spreadsheet with rbcid, age, sex, study_site, mean_fd --> harmonization variables

demographics <- demographics[demographics$rbcid %in% participants$rbcid,] #covariates and site for final sample only

#### Prepare Diffusion Measure Spreadsheets ####

# Read in tract measures csv and create measure-specific spreadsheets
tractmeasures.glasser.hbn <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_thalamocortical_measures.csv") #generated by tract_measures/diffusion_metrics/thalamocortical_dwimeasures.py

# Function to create measure-specific spreadsheets given long-formatted tract measure df and a dsi-studio measure of interest
extract_measure <- function(input.df, measure){ 
  measure.df <- get(input.df) %>% select(rbcid, tract, all_of(measure)) #extract measure of interest, long df
  measure.df <- measure.df %>% arrange(tract) #tracts in alphabetical order 
  measure.df <- measure.df %>% pivot_wider(names_from = "tract", values_from = all_of(measure)) #long to wide format, all participants and tracts
  measure.df <- measure.df %>% arrange(rbcid) #rbcids in numerical order
  measure.df <- left_join(demographics, measure.df, by = "rbcid") #final sample participants, all tracts + demographics
  colnames(measure.df) <- gsub("-", "_", colnames(measure.df))
  return(measure.df)
}

FA.glasser.hbn <- extract_measure(input.df = "tractmeasures.glasser.hbn", measure = "dti_fa")

MD.glasser.hbn <- extract_measure(input.df = "tractmeasures.glasser.hbn", measure = "md")

streamlinecount.glasser.hbn <- extract_measure(input.df = "tractmeasures.glasser.hbn", measure = "number_of_tracts")
write.csv(streamlinecount.glasser.hbn, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_streamlinecount_finalsample.csv", quote = F, row.names = F)

#### Perform Combat Harmonization ####

#https://github.com/Jfortin1/neuroCombat_Rpackage/tree/2ccab2b42c59163717f012c70a54d20e8757b1c7 
#dat = pxn matrix of observations, p rows are features (here, tracts) and n columns are participants
#batch = a numeric or character vector of length n indicating batch (here, site)
#mod = model matrix of biological covariates, including the outcome of interest (here, age)
  # mod <- model.matrix(~ age + sex + mean_fd) 
  # mod contains intercept, age, mean_fd, sex #combat removes intercept from model matrix
  
# The harmonized matrix is stored in output$dat.combat

combat.input.fa <- t(FA.glasser.hbn %>% select(contains("autotrack"))) #238 rows of tracts, columns are participants
batch.input.fa <- FA.glasser.hbn$study_site
mod.input.fa <- model.matrix(~ FA.glasser.hbn$age + FA.glasser.hbn$sex + FA.glasser.hbn$mean_fd)
fa.harmonized.combat <- neuroCombat(dat = combat.input.fa, batch = batch.input.fa, mod = mod.input.fa)
FA.harmonized.hbn <- fa.harmonized.combat$dat.combat %>% t() %>% data.frame() #rows are participants, 238 columns of tracts
FA.harmonized.hbn <- cbind(FA.glasser.hbn[,1:5], FA.harmonized.hbn)
FA.glasser.hbn <- FA.harmonized.hbn

combat.input.md <- t(MD.glasser.hbn %>% select(contains("autotrack"))) #238 rows of tracts, columns of participants
batch.input.md <- MD.glasser.hbn$study_site
mod.input.md <- model.matrix(~ MD.glasser.hbn$age + MD.glasser.hbn$sex + MD.glasser.hbn$mean_fd)
md.harmonized.combat <- neuroCombat(dat = combat.input.md, batch = batch.input.md, mod = mod.input.md)
MD.harmonized.hbn <- md.harmonized.combat$dat.combat %>% t() %>% data.frame()
MD.harmonized.hbn <- cbind(MD.glasser.hbn[,1:5], MD.harmonized.hbn)
MD.glasser.hbn <- MD.harmonized.hbn

#### Create Final Diffusion Measure Spreadsheets Thresholded by Streamline Count ####
## Goal here is to NA out FA/MD information for connections with <5 streamlines (primary analysis) or <10 streamlines (sensitivity analysis), leaving dfs with only to-be-analyzed connections

# First, ensure that order of variables/tracts and rbcids is equivalent across dfs
identical(names(FA.glasser.hbn), names(streamlinecount.glasser.hbn))
identical(FA.glasser.hbn$rbcid, streamlinecount.glasser.hbn$rbcid)
identical(names(MD.glasser.hbn),names(streamlinecount.glasser.hbn))
identical(MD.glasser.hbn$rbcid, streamlinecount.glasser.hbn$rbcid)

# Next, threshold streamline count 
## primary threshold
streamlinecount.threshold5 <- ifelse(streamlinecount.glasser.hbn[,6:243] >= 5, 1, NA) %>% data.frame() #set tracts with < 5 streamlines to NA, 6:243 cols are the tract cols

FA.glasser.hbn.primary <- FA.glasser.hbn[,6:243] * streamlinecount.threshold5 #don't analyze connections with < 5 streamlines. #rbcid order and tract order are identical between multiplied dfs
FA.glasser.hbn.primary <- cbind(FA.glasser.hbn[,1:5], FA.glasser.hbn.primary)
write.csv(FA.glasser.hbn.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_FA_finalsample_primary.csv", quote = F, row.names = F)

MD.glasser.hbn.primary <- MD.glasser.hbn[,6:243] * streamlinecount.threshold5 
MD.glasser.hbn.primary <- cbind(MD.glasser.hbn[,1:5], MD.glasser.hbn.primary)
write.csv(MD.glasser.hbn.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_MD_finalsample_primary.csv", quote = F, row.names = F)

## sensitivity threshold
streamlinecount.threshold10 <- ifelse(streamlinecount.glasser.hbn[,6:243] >= 10, 1, NA) %>% data.frame() 

FA.glasser.hbn.sensitivity <- FA.glasser.hbn[,6:243] * streamlinecount.threshold10 
FA.glasser.hbn.sensitivity <- cbind(FA.glasser.hbn[,1:5], FA.glasser.hbn.sensitivity)
write.csv(FA.glasser.hbn.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_FA_finalsample_sensitivity.csv", quote = F, row.names = F)

MD.glasser.hbn.sensitivity <- MD.glasser.hbn[,6:243] * streamlinecount.threshold10 
MD.glasser.hbn.sensitivity <- cbind(MD.glasser.hbn[,1:5], MD.glasser.hbn.sensitivity)
write.csv(MD.glasser.hbn.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/HBN/HBN_MD_finalsample_sensitivity.csv", quote = F, row.names = F)

