#### PNC Sensitivity Analyses DF Creation ####
library(dplyr)
library(tidyr)
library(tidyverse)
library(arrow)
library(purrr)

## Goal here is to get surface area, SNR, and overlap measures for final PNC sample for only analyzed connections

# PNC final sample 
participants <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/PNC_thalamocortical_finalsample_N1145.csv")

# Thalamocortical atlas tract list
atlas.tracts <- read.csv("/cbica/projects/thalamocortical_development/software/thalamocortical_autotrack_template/dsi-studio/atlas/ICBM152_adult/ICBM152_adult.tt.gz.txt", header = F) %>% set_names("tract") #list of thalamocortical atlas tracts

# Connection-level streamline count data
streamlinecount.glasser.pnc <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_streamlinecount_finalsample.csv") %>% select(rbcid, contains("autotrack"))
streamlinecount.rbcids <- streamlinecount.glasser.pnc %>% select(rbcid)
streamlinecount.glasser.pnc <- streamlinecount.glasser.pnc %>% select(contains("autotrack"))

## Functions

extract_measure <- function(metric.df, participants.df, measure){ 
  measure.df <- metric.df %>% select(rbcid, tract, all_of(measure)) #extract measure of interest from long df
  measure.df <- measure.df %>% arrange(tract) #tracts in alphabetical order 
  measure.df <- measure.df %>% pivot_wider(names_from = "tract", values_from = all_of(measure)) #long to wide format, all participants and tracts
  measure.df <- measure.df %>% arrange(rbcid)  #rbcids in numerical order
  colnames(measure.df) <- gsub("-", "_", colnames(measure.df))
  measure.df <- measure.df[measure.df$rbcid %in% participants.df$rbcid,] %>% as.data.frame() #only final sample of participants now
  return(measure.df)
}

#### Regional Surface Area ####

# Read in glasser parcel anatomy data
anatomy.pnc.long <- arrow::read_parquet("/cbica/projects/thalamocortical_development/cortical_anatomy/individual/PNC/pnc_glasser_surfacestats.parquet") %>% 
               rename(rbcid = subject_id) %>% select(rbcid, StructName, SurfArea) %>% filter(StructName != "???") #freesurfer area in glasser regions 
anatomy.pnc.long$tract <- paste0("thalamus-", anatomy.pnc.long$StructName) %>% gsub("_ROI", "-autotrack", .) #create tract variable matching atlas tract format
anatomy.pnc.long <- anatomy.pnc.long %>% select(-StructName)
anatomy.pnc.long <- anatomy.pnc.long[anatomy.pnc.long$tract %in% atlas.tracts$tract,]

# Create wide df with tract-specific surface area measures (for the thalamocortical tract's cortical endpoint)
anatomy.pnc <- extract_measure(metric.df = anatomy.pnc.long, participants.df = participants, measure = "SurfArea")

# Remove regions with < 5 streamlines from analysis  
if(identical(anatomy.pnc$rbcid, streamlinecount.rbcids$rbcid)) {print("identical rbcid order for surface area")}
if(identical(names(anatomy.pnc[,2:239]), names(streamlinecount.glasser.pnc))) {print("identical tract order for surface area")}
anatomy.pnc[,2:239] <- anatomy.pnc[,2:239] * ifelse(streamlinecount.glasser.pnc >= 5, 1, NA)

# Save csv
write.csv(anatomy.pnc, "/cbica/projects/thalamocortical_development/cortical_anatomy/individual/PNC/PNC_surfacearea_finalsample.csv", quote = F, row.names = F)

#### SNR ####

# Read in connection SNR data
snr.pnc.long <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_thalamicconnection_SNR.csv") #generated by /tract_measures/snr/thalamocortical_SNRvalues shell and python scripts

# Create wide df with tract-specific SNR measures
snr.pnc <- extract_measure(metric.df = snr.pnc.long, participants.df = participants, measure = "SNR")

# Remove tracts with < 5 streamlines from analysis
if(identical(snr.pnc$rbcid, streamlinecount.rbcids$rbcid)) {print("identical rbcid order for snr")}
if(identical(names(snr.pnc[,2:239]), names(streamlinecount.glasser.pnc))) {print("identical tract order for snr")}
snr.pnc[,2:239] <- snr.pnc[,2:239] * ifelse(streamlinecount.glasser.pnc >= 5, 1, NA)

# Save csv
write.csv(snr.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_SNR_finalsample.csv", quote = F, row.names = F)

#### Sensitivity and specificity ####

# Read in connection overlap data
overlap.pnc.long <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_thalamicconnection_overlap.csv") #generated by /tract_measures/overlap/thalamocortical_sensitivityspecificity.py

# Create wide df with tract-specific overlap measures
sensitivity.pnc <- extract_measure(metric.df = overlap.pnc.long, participants.df = participants, measure = "sensitivity")
specificity.pnc <- extract_measure(metric.df = overlap.pnc.long, participants.df = participants, measure = "specificity")

# Remove tracts with < 5 streamlines from analysis
if(identical(sensitivity.pnc$rbcid, streamlinecount.rbcids$rbcid)) {print("identical rbcid order for sensitivity")}
if(identical(names(sensitivity.pnc[,2:239]), names(streamlinecount.glasser.pnc))) {print("identical tract order for sensitivity")}
sensitivity.pnc[,2:239] <- sensitivity.pnc[,2:239] * ifelse(streamlinecount.glasser.pnc >= 5, 1, NA)

if(identical(specificity.pnc$rbcid, streamlinecount.rbcids$rbcid)) {print("identical rbcid order for specificity")}
if(identical(names(specificity.pnc[,2:239]), names(streamlinecount.glasser.pnc))) {print("identical tract order for specificity")}
specificity.pnc[,2:239] <- specificity.pnc[,2:239] * ifelse(streamlinecount.glasser.pnc >= 5, 1, NA)

# Save csv
write.csv(sensitivity.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_overlapsensitivity_finalsample.csv", quote = F, row.names = F)
write.csv(specificity.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_overlapspecificity_finalsample.csv", quote = F, row.names = F)




