#### PNC Diffusion Measure DF Creation ####
library(dplyr)
library(tidyr)

#### Prepare Demographics Data ####
## Goal here is to get demographics data that will be used in model fitting for the final PNC study sample

# PNC final sample 
participants <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/PNC_thalamocortical_finalsample_N1145.csv")

# Read in demographics and diffusion motion metrics
demographics <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/n1601_demographics_go1_20161212.csv")
demographics <- merge(participants, demographics, by = "scanid") #demographics for the final sample, with rbcid and scanid
demographics <- demographics %>% mutate(age = (ageAtScan1/12)) #convert age from months to years
demographics <- demographics %>% select(rbcid, age, sex)
demographics$sex <- as.factor(demographics$sex) #factor 

dwi.qc <- read.csv("/cbica/projects/thalamocortical_development/sample_info/PNC/PNC_DWI_QCmetrics.csv") #diffusion scan acquisition parameters and quality metrics, generated by sample_construction/PNC/diffusion_qcmetrics_PNC.py
dwi.qc <- dwi.qc %>% select(subject_id, mean_fd) #just need these
colnames(dwi.qc) <- c("rbcid", "mean_fd")
demographics <- merge(demographics, dwi.qc, by = "rbcid")

#### Prepare Diffusion Measure Spreadsheets ####
## Goal here is to combine rbcid, age, sex, mean_fd with dwi measures of interest

# Read in tract measures csv to create measure-specific spreadsheets
tractmeasures.glasser.pnc <- read.csv("/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_thalamocortical_measures.csv") #generated by tract_measures/diffusion_metrics/thalamocortical_dwimeasures.py

# Function to create measure-specific spreadsheets given long-formatted tract measure df and a dsi-studio measure of interest
extract_measure <- function(input.df, measure){ 
  measure.df <- get(input.df) %>% select(rbcid, tract, all_of(measure)) #extract measure of interest, long df
  measure.df <- measure.df %>% arrange(tract) #tracts in alphabetical order 
  measure.df <- measure.df %>% pivot_wider(names_from = "tract", values_from = all_of(measure)) #long to wide format, all participants and tracts
  measure.df <- measure.df %>% arrange(rbcid) #rbcids in numerical order
  measure.df <- left_join(demographics, measure.df, by = "rbcid") #final sample participants, all tracts + demographics
  colnames(measure.df) <- gsub("-", "_", colnames(measure.df))
  return(measure.df)
}

FA.glasser.pnc <- extract_measure(input.df = "tractmeasures.glasser.pnc", measure = "dti_fa")

MD.glasser.pnc <- extract_measure(input.df = "tractmeasures.glasser.pnc", measure = "md")

streamlinecount.glasser.pnc <- extract_measure(input.df = "tractmeasures.glasser.pnc", measure = "number_of_tracts")
write.csv(streamlinecount.glasser.pnc, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_streamlinecount_finalsample.csv", quote = F, row.names = F) #original streamline count data

#### Create Final Diffusion Measure Spreadsheets Thresholded by Streamline Count ####
## Goal here is to NA out FA/MD information for connections with <5 streamlines (primary analysis) or <10 streamlines (sensitivity analysis), leaving dfs with only to-be-analyzed connections

# First, ensure that order of variables/tracts and rbcids is equivalent across dfs
identical(names(FA.glasser.pnc), names(streamlinecount.glasser.pnc))
identical(FA.glasser.pnc$rbcid, streamlinecount.glasser.pnc$rbcid)
identical(names(MD.glasser.pnc),names(streamlinecount.glasser.pnc))
identical(MD.glasser.pnc$rbcid, streamlinecount.glasser.pnc$rbcid)

# Next, threshold streamline count 
## primary threshold
streamlinecount.threshold5 <- ifelse(streamlinecount.glasser.pnc[,5:242] >= 5, 1, NA) %>% data.frame() #set tracts with < 5 streamlines to NA

FA.glasser.pnc.primary <- FA.glasser.pnc[,5:242] * streamlinecount.threshold5 #don't analyze connections with < 5 streamlines. #rbcid order and tract order are identical between multiplied dfs
FA.glasser.pnc.primary <- cbind(FA.glasser.pnc[,1:4], FA.glasser.pnc.primary)
write.csv(FA.glasser.pnc.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_FA_finalsample_primary.csv", quote = F, row.names = F)

MD.glasser.pnc.primary <- MD.glasser.pnc[,5:242] * streamlinecount.threshold5 
MD.glasser.pnc.primary <- cbind(MD.glasser.pnc[,1:4], MD.glasser.pnc.primary)
write.csv(MD.glasser.pnc.primary, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_MD_finalsample_primary.csv", quote = F, row.names = F)

## sensitivity threshold
streamlinecount.threshold10 <- ifelse(streamlinecount.glasser.pnc[,5:242] >= 10, 1, NA) %>% data.frame()

FA.glasser.pnc.sensitivity <- FA.glasser.pnc[,5:242] * streamlinecount.threshold10
FA.glasser.pnc.sensitivity <- cbind(FA.glasser.pnc[,1:4], FA.glasser.pnc.sensitivity)
write.csv(FA.glasser.pnc.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_FA_finalsample_sensitivity.csv", quote = F, row.names = F)

MD.glasser.pnc.sensitivity <- MD.glasser.pnc[,5:242] * streamlinecount.threshold10 
MD.glasser.pnc.sensitivity <- cbind(MD.glasser.pnc[,1:4], MD.glasser.pnc.sensitivity)
write.csv(MD.glasser.pnc.sensitivity, "/cbica/projects/thalamocortical_development/thalamocortical_structuralconnectivity/individual/PNC/PNC_MD_finalsample_sensitivity.csv", quote = F, row.names = F)
